### ISSUE TITLE
(idea) Have a max speed of 34 blocks/sec to match elytra speed

### ISSUE THREAD

**Issue by llakala** [Patbox/TaterCart#4]
Having the speed around 34 blocks per second makes it so minecarts are a reliable transport system for large maps, but aren't too overpowered and match elytra speed well.

**Comment by diznover** [comment]
You can do it with this [mod](https://www.curseforge.com/minecraft/mc-mods/speed-carts), and with this [mod](https://www.curseforge.com/minecraft/mc-mods/audaki-cart-engine)

**Comment by Patbox** [comment]
TaterCart already speed ups minecarts. Could speed them up even more to be fair

**Comment by diznover** [comment]
There are already 2 mods for this, I think while these mods are held do not conflict with TaterCart you can leave everything as it is.

**Comment by Patbox** [comment]
While they don't conflict now (through you can't be sure with that, since we change same part of game) they might break mechanics of TaterCart

**Comment by Patbox** [comment]
Technically not by default, but you can now set it with gamerules
