### ISSUE TITLE
[ Feature ] Add configurable minecart speeds with signs

### ISSUE THREAD

**Issue by zndrmn** [Patbox/TaterCart#5]
Add a way to change the speed of minecarts in game with the use of signs. something like this server side mod [https://www.curseforge.com/minecraft/mc-mods/speed-carts](https://www.curseforge.com/minecraft/mc-mods/speed-carts)

**Comment by zndrmn** [comment]
also server sided config with min and max minecart speeds would be nice

example: 
min 8 - max 32 / min 1 - max 128 etc
player can only choose speeds within that range in game

**Comment by Patbox** [comment]
Instead of signs, it's implemented with new rail type
