### ISSUE TITLE
[Issue] Mod crashes

### ISSUE THREAD

**Issue by Nekkok** [Patbox/TaterCart#6]
I have no clue why, but I tried disabling some mods in my modlist and have no clue what the logs is refering to. I'm sharing it because I would love to play with it :C
[latest.log](https://github.com/Patbox/TaterCart/files/8794363/latest.log)

Thank you

**Comment by Patbox** [comment]
It is mod incompatibility. Try disabling mods until it works (or find one that changes minecarts, mostly in area of item drops)

**Comment by Nekkok** [comment]
Found the culprit! Or so I think... it was dropfullcarts by altrisi or maybe any other mod that could fix any other issue with the same feature that could create a conflict. Btw, the sprites of the items look corrupted, like they don't have any proper skin. I'm sending you a screenshot so you can tell me if this is normal, but I think is worth noticing. Thank you again!

![javaw_5v83o3a2hI](https://user-images.githubusercontent.com/28939799/171289549-0725d855-3ef8-41fa-aff8-014cd577408d.png)

**Comment by Patbox** [comment]
They look right. Since this mod was designed to work with vanilla clients on modded server. Ofc it works on single, but I didn't make any textures yet
